"""
Convert persona vectors (.pt format) to EasySteer-compatible GGUF format.

This script converts the persona vectors generated by the persona_vectors repo
into the GGUF format that EasySteer expects for inference.
"""

import os
import sys
import argparse
import torch
import numpy as np
from pathlib import Path

# Add EasySteer to path
sys.path.insert(0, str(Path(__file__).parent / "EasySteer"))
from EasySteer.easysteer.steer import StatisticalControlVector


def convert_persona_vector_to_gguf(
    pt_path: str,
    output_path: str,
    model_type: str = "qwen2.5",
    method: str = "persona_diffmean",
):
    """
    Convert a persona vector .pt file to GGUF format.

    Args:
        pt_path: Path to the .pt file (shape: [num_layers, hidden_dim])
        output_path: Path to save the .gguf file
        model_type: Model type identifier (e.g., "qwen2.5", "llama")
        method: Method used to generate the vector
    """
    print(f"Loading persona vector from {pt_path}...")

    # Load the .pt file
    vector = torch.load(pt_path, map_location="cpu", weights_only=False)

    # Check shape
    print(f"Vector shape: {vector.shape}")
    if vector.ndim != 2:
        raise ValueError(f"Expected 2D tensor [layers, hidden_dim], got shape {vector.shape}")

    num_layers, hidden_dim = vector.shape
    print(f"Number of layers: {num_layers}, Hidden dimension: {hidden_dim}")

    # Convert to the format EasySteer expects
    # EasySteer uses a dict mapping layer_idx -> numpy array of shape (hidden_dim,)
    directions = {}
    for layer_idx in range(num_layers):
        directions[layer_idx] = vector[layer_idx].float().numpy()

    # Create StatisticalControlVector
    control_vector = StatisticalControlVector(
        model_type=model_type,
        method=method,
        directions=directions,
        metadata={
            "num_layers": num_layers,
            "hidden_dim": hidden_dim,
        }
    )

    # Export to GGUF
    print(f"Exporting to {output_path}...")
    control_vector.export_gguf(output_path)
    print(f"Successfully converted! Saved to {output_path}")


def main():
    parser = argparse.ArgumentParser(description="Convert persona vectors to GGUF format")
    parser.add_argument(
        "--input",
        type=str,
        required=True,
        help="Path to input .pt file"
    )
    parser.add_argument(
        "--output",
        type=str,
        required=True,
        help="Path to output .gguf file"
    )
    parser.add_argument(
        "--model-type",
        type=str,
        default="qwen2.5",
        help="Model type identifier (default: qwen2.5)"
    )
    parser.add_argument(
        "--method",
        type=str,
        default="persona_diffmean",
        help="Method name (default: persona_diffmean)"
    )

    args = parser.parse_args()

    # Create output directory if needed
    os.makedirs(os.path.dirname(args.output), exist_ok=True)

    convert_persona_vector_to_gguf(
        pt_path=args.input,
        output_path=args.output,
        model_type=args.model_type,
        method=args.method,
    )


if __name__ == "__main__":
    main()
